name = "numeron"
compatibility_date = "2025-05-02"

[build]
command = "npm run build"
[build.upload]
format = "directory"
dir = "./dist"

[site]
bucket = "./dist"
entry-point = "functions"

[[plugins]]
name = "cloudflare-pages-functions"

[[kv_namespaces]]
binding = "GAME_KV"
id = "56ead805eaa944f8bcee56c2bec1a809"   # 開発環境用のID (Dev)
preview_id = "ec463fbcc8cd4eb3b6bec41be1ece334" # preview 用 (wrangler dev 用)